---
- name: demo
  hosts: inventories_switch

  tasks:
    - name: run show interface on remote devices
      ios_command:
        commands: show int status
      register: demo
    - debug: var=demo.stdout_lines
