---
- name: show interface status
  hosts: inventories_switch
  gather_facts: no

  tasks:
    - name: run show interface status on remote devices
      os6_command:
        commands: show int status
        wait_for: result[0] contains Dells
