---
- name: show interface status
  hosts: all
  gather_facts: no

  tasks:
    - name: run show interface status on remote devices
      os6_command:
        commands: show int status
      register: demo
    - debug: var=demo.stdout_lines
